[helpers]

### Package group mappings ###

[os]
depends = ["boot", "base-os", "base-os-dracut", "base-os-greet", "base-os-gentoo-accept-keywords", "base-os-gentoo-package-use", "base-os-gentoo-env-override", "my-scripts", "base-os-systemd-unit-dropins"]

[user]
depends = ["misc-home", "sway", "waybar", "wofi", "fish", "ssh"]

### END Package group mappings ###


### OS level files ###

# Not templates but using this type to copy a file vs create a symlink
# See:
# https://github.com/SuperCuber/dotter/issues/77

[boot]

[boot.files]
"boot/systemd-boot-config" = { target = "/efi/loader/loader.conf", type = "template" }

[base-os]

[base-os.files]
"base-os/make.conf" = { target = "/etc/portage/make.conf", type = "template" }
"base-os/gentoo-package-license" = { target = "/etc/portage/package.license", type = "template" }
"base-os/sysctl-docker" = { target = "/etc/sysctl.d/docker.conf",  type = "template" }
"base-os/secutity-limits.d/70-audio.conf" = { target = "/etc/security/limits.d/70-audio.conf",  type = "template" }
"base-os/tmpfiles-energy-perf" = { target = "/etc/tmpfiles.d/energy_performance_preference.conf", type = "template" }
"base-os/modprobe-iwlwifi" = { target = "/etc/modprobe.d/iwlwifi.conf", type = "template" }
#
# Custom sysusers frile for tss to fix bug:
# https://bugs.gentoo.org/925524
"base-os/sysusers-tpm2-tss-config" = { target = "/usr/lib/sysusers.d/tpm2-tss.conf", type = "template" }

[base-os-dracut]

[base-os-dracut.files]
"base-os/dracut/cmd-line.conf" = { target = "/etc/dracut.conf.d/cmd-line.conf",  type = "template" }
"base-os/dracut/firmware-blobs.conf" = { target = "/etc/dracut.conf.d/firmware-blobs.conf",  type = "template" } 
"base-os/dracut/microcode.conf" = { target = "/etc/dracut.conf.d/microcode.conf", type = "template" }
"base-os/dracut/modules.conf" = { target = "/etc/dracut.conf.d/modules.conf",  type = "template" }

[base-os-greet]

[base-os-greet.files]
"base-os/greet/config.toml" = { target = "/etc/greetd/config.toml",  type = "template" }
"base-os/greet/environments" = { target = "/etc/greetd/environments",  type = "template" }
"base-os/greet/gtkgreet.css" = { target = "/etc/greetd/gtkgreet.css",  type = "template" }
"base-os/greet/sway-config" = { target = "/etc/greetd/sway-config", type = "template" }
#
# Gentoo is missing the PAM dropin for greetd
"base-os/greet/pam-dropin" = { target = "/etc/pam.d/greetd", type = "template" }

[base-os-gentoo-accept-keywords]

[base-os-gentoo-accept-keywords.files]
"base-os/gentoo-accept-keywords/10-base-os" = { target = "/etc/portage/package.accept_keywords/10-base-os", type = "template" }
"base-os/gentoo-accept-keywords/55-virtualization" = { target =  "/etc/portage/package.accept_keywords/55-virtualization", type = "template" }
"base-os/gentoo-accept-keywords/60-desktop-apps" = { target = "/etc/portage/package.accept_keywords/60-desktop-apps",  type = "template" }

[base-os-gentoo-package-use]

[base-os-gentoo-package-use.files]
"base-os/gentoo-package-use/00-cpu-flags" = { target = "/etc/portage/package.use/00-cpu-flags", type = "template" }
"base-os/gentoo-package-use/01-python-targets" = { target = "/etc/portage/package.use/01-python-targets", type = "template" }
"base-os/gentoo-package-use/10-base-os" = { target = "/etc/portage/package.use/10-base-os", type = "template" }
"base-os/gentoo-package-use/20-base-apps" = { target = "/etc/portage/package.use/20-base-apps",  type = "template" }
"base-os/gentoo-package-use/30-x11-enabled" = { target = "/etc/portage/package.use/30-x11-enabled", type = "template" }
"base-os/gentoo-package-use/40-window-manager" = { target = "/etc/portage/package.use/40-window-manager", type = "template" }
"base-os/gentoo-package-use/50-networking" = { target = "/etc/portage/package.use/50-networking", type = "template" }
"base-os/gentoo-package-use/55-virtualization" = { target = "/etc/portage/package.use/55-virtualization", type = "template" }
"base-os/gentoo-package-use/60-desktop-apps" = { target = "/etc/portage/package.use/60-desktop-apps", type = "template" }
"base-os/gentoo-package-use/65-fonts" = { target = "/etc/portage/package.use/65-fonts", type = "template" }
"base-os/gentoo-package-use/70-dev-tools" = { target = "/etc/portage/package.use/70-dev-tools", type = "template" }

[base-os-gentoo-env-override]

[base-os-gentoo-env-override.files]
"base-os/gentoo-env/force-makefile-sequential-builds.conf" = { target = "/etc/portage/env/force-makefile-sequential-builds.conf", type = "template" }
"base-os/gentoo-env/makefile-sequential-builds" = { target = "/etc/portage/package.env/makefile-sequential-builds", type = "template" }

[base-os-systemd-unit-dropins]

[base-os-systemd-unit-dropins.files]
"base-os/systemd-unit-dropins/network-manager-set-logging-to-warn" = { target = "/etc/systemd/system/NetworkManager.service.d/set-logging-to-warn.conf", type = "template" }
"base-os/systemd-unit-dropins/rtkit-set-realtime-prio" = { target = "/etc/systemd/system/rtkit-daemon.service.d/enable-realtime.conf", type = "template" }

[base-os-power-managment]

[base-os-power-managment.files]
"base-os/power-managment/00-my-defaults.conf" = { target = "/etc/tlp.d/00-my-defaults.conf", type = "template" }
"base-os/power-managment/10-ac-dock-caldigit.conf" = { target = "/etc/tlp.d/10-ac-dock-caldigit.conf", type = "template" }
"base-os/power-managment/logind.conf" = { target = "/etc/systemd/logind.conf", type = "template" }

[udev-rules]

[udev-rules.files]
"base-os/udev-rules/70-jabra.rules" = { target = "/etc/udev/rules.d/70-jabra.rules", type = "template" }

[my-scripts]

[my-scripts.files]
"my-scripts/screenshot.sh" = { target = "/usr/local/bin/screenshot.sh", type = "template" }
"my-scripts/sway_window_split_indicator.py" = { target = "/usr/local/bin/sway_window_split_indicator.py", type = "template" }
"my-scripts/launch-chrome-with-gpu-offload" = { target = "/usr/local/bin/meets", type = "template" }

### END OS level files ###


### User /home config and dot files ###

[misc-home]

[misc-home.files]
"desktop/user-dot-profile" = "~/.profile"
"desktop/gtk3-settings" = "~/.config/gtk-3.0/settings.ini"
"desktop/wezterm-config" = "~/.config/wezterm/wezterm.lua"
"desktop/gpg-conf" =  "~/.gnupg/gpg.conf"
"desktop/htop-config" = "~/.config/htop/htoprc"
"desktop/kanshi-config" = "~/.config/kanshi/config"

[sway]

[sway.files]
"desktop/sway/config" = "~/.config/sway/config"
"desktop/sway/launch-supporting-apps" = "~/.config/sway/config.d/launch-supporting-apps"
"desktop/sway/custom-key-binds" = "~/.config/sway/config.d/custom-key-binds"
"desktop/sway/systemd-user-env" = "~/.config/sway/config.d//systemd-user-env"

[waybar]

[waybar.files]
"desktop/waybar/config" = { target = "~/.config/waybar/config", type = "template" }
"desktop/waybar/style.css" = "~/.config/waybar/style.css"

[wofi]

[wofi.files]
"desktop/wofi/config" = "~/.config/wofi/config"
"desktop/wofi/config.grimshot" = "~/.config/wofi/config.grimshot"
"desktop/wofi/style.css" = "~/.config/wofi/style.css"

[mako]

[mako.files]
"desktop/mako/comfig" = "~/.config/mako/config"

[fish]

[fish.files]
"desktop/fish/config.fish" = "~/.config/fish/config.fish"
"desktop/fish/vscode-integration.fish" = "~/.config/fish/conf.d/vscode-integration.fish"
"desktop/fish/misc.fish" = "~/.config/fish/conf.d/misc.fish"
"desktop/fish/git.fish" = "~/.config/fish/conf.d/git.fish"

[ssh]

[ssh.files]
"desktop/ssh-config" = "~/.ssh/config"


### END User /home config and dot files ###
