# Host name based include file
# Use local.tml to override any sensitive items
includes = []
packages = ["user"]

[files]
"desktop/sway/launch-host-smd-apps" = "~/.config/sway/config.d/launch-host-smd-apps"

[variables]
